### PR TITLE
Update bootstrap.md

### PR DESCRIPTION
**Pull request by planthaber**
Sorted for a better overview, converted to github flavored markdown

### CODE REVIEW

**Comment by planthaber** [comment]
hmm, guess keeping the css instead of github flavored markdown better fits the overall look.

Or can be change the css of that one directly? That way it would be easier to contribute

**Comment by 2maz** [comment]
The page still looks a bit inconsistent. Could you check on the alignment of the second bash block and
could you also point to using
```
ruby autoproj_bootstrap --help
```
Then followed by the examples.

**Comment by planthaber** [comment]
renewed the layout, and added extra headline for examples

**Comment by planthaber** [comment]
btw: compared to

https://github.com/rock-core/rock-core.github.io/blob/planthaber-patch-1/documentation/autoproj/bootstrap.md

my local jekyll renders the enumerations correctly

**Pull request merged**
