### PR TITLE
Add dev bootstrap

### PR DESCRIPTION
**Pull request by 2maz**
Add developer bootstrap script that directly points to autoproj and autobuild github versions, as well as the patched qtbindings

### CODE REVIEW

**Comment by planthaber** [comment]
Had to merge in order to start testing, seems like the qtbindings are installed right away with autoproj, even tough it is not a dependency of autoproj. Installation with dev fails because no dependencies of qtbindings are installed (like e.g. qt4)

**Comment by planthaber** [comment]
installing them manually gets me a step further:

sudo apt-get install ruby-dev software-properties-common 
sudo add-apt-repository ppa:rock-core/qt4
sudo apt update
sudo apt-get install libqt4-*

**Comment by doudou** [comment]
>  as well as the patched qtbindings

Not sure how is that relevant ?

Anyways, the problem with qtbindings always being installed is essentially the reason why it's not merged in the package set's master. qtbindings is forcefully added in the gemfile, instead of being injected via osdeps. Support for gem-from-git in autoproj welcome.

**Comment by planthaber** [comment]
Is there already another issue to discuss this?
The ability to use a dev bootstrap is imo unrelated to how the current dev bootstrap works.

**Comment by doudou** [comment]
> The ability to use a dev bootstrap is imo unrelated to how the current dev bootstrap works.

That was my point with "Not sure how is that relevant ?". The updated bootstrap is not needed for anything related to focal (that I can see ...). Moreover, even the non-master bootstrap script bootstraps the latest version of autoproj (same than the master bootstrap script).

Essentially, I see the two things (this PR and focal-compatible qt4/qtbindings) are completely orthogonal issues. Was wondering if I was missing something

**Comment by doudou** [comment]
> Is there already another issue to discuss this?

Not really. See this thread: https://github.com/rock-core/package_set/pull/170#discussion_r426667447

**Comment by doudou** [comment]
FYI, https://github.com/rock-core/autoproj/pull/333 and https://github.com/rock-core/package_set/pull/194

The second needs the first to be merged & released. I would appreciate it if you guys could check that the autoproj pull request behaves properly with your osdeps files. It works with the "standard" one, but there is bound to be some creative structures somewhere that it would break.

**Comment by planthaber** [comment]
Seems to work fine with these:

Using autobuild 1.22.0 from https://github.com/rock-core/autobuild.git (at master@eeb6569)
Using autoproj 2.14.0 from https://github.com/rock-core/autoproj.git (at gem_from_git@4e7853d)

**Comment by doudou** [comment]
Thanks !

**Pull request merged**
