### PR TITLE
Reactive package listing

### PR DESCRIPTION
**Pull request by 2maz**
Added a page for package search using just the information available from github - see test setup
https://2maz.github.io/documentation/about/packages.html

### CODE REVIEW

**Comment by doudou** [comment]
Cool. Wanted to do something like that for a long time.

Just FYI, what I was envisioning, to avoid hitting the REST API too hard, was rather to have a daemon process generate a JSON file (on CI or something like this), which is then read by the page.

**Comment by 2maz** [comment]
> Just FYI, what I was envisioning, to avoid hitting the REST API too hard, was rather to have a daemon process generate a JSON file (on CI or something like this), which is then read by the page.

Also thought about it, but as a first shot I intentionally tried to avoid having a build server/daemon dependency. Less complexity / maintenance, more recent results - at least when looking at our past experience with maintaining the website.

Regarding the daemon we could link with the CI on package_set updates, e.g., to provide the package to package_set mapping.

**Comment by doudou** [comment]
> Regarding the daemon we could link with the CI on package_set updates, e.g., to provide the package to package_set mapping.

We have a full CI setup (all of the underlying code is public, but lack of documentation and stuff), as well as a standalone daemon that listens to changes to the repositories. There are still a few kinks, but I'll try to send an email to rock-core/rock-users to advertise it a bit.

**Review by doudou — APPROVED** [review]

**Comment by doudou** [comment]
To be clear, this is a LOT better than the current status quo, so all :+1:

**Comment by planthaber** [comment]
> to avoid hitting the REST API too hard

@doudou FYI, just in case you haven't senn that:

The API result is buffered in the Browser's "local storage" (html5 feature) with a timestamp. The API itself is not used on every reload.

**Comment by doudou** [comment]
> @doudou FYI, just in case you haven't senn that:

I did see. From a quick reading, I thought you were trying to read all the manifests, but I just realized that you probably do it only on click ... So that's really not that bad.

**Pull request merged**
